services:
  db:
    container_name: weather-tracker-db
    image: postgres:16-alpine
    env_file:
      - .env.prod
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  app:
    container_name: weather-tracker-app
    image: asalavei/weather-tracker:latest
    env_file:
      - .env.prod
    depends_on:
      db:
        condition: service_healthy
    restart: always
    ports:
      - "80:8080"